include:
  - project: 'platform/pipelines-templates'
    file: '/build/node/template-node-npm.yml'
    ref: master

install-dependencies:
  stage: prepare

  before_script:
    - npm version

  script:
    - echo "${PRIVATE_NPM_REGISTRY_TOKEN}" > ${HOME}/.npmrc
    - npm ci

  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - node_modules

test:
  stage: test

  coverage: '/^Statements\s*:\s*([^%]+)/'
  script:
    - npm run lint
    - npm run build --if-present
    - npm run coverage

  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - node_modules
    policy: pull

  artifacts:
    reports:
      cobertura: coverage/cobertura-coverage.xml

.docker-job:

  variables:
    COMMIT_SHA_FILEPATH: /usr/static/commit.sha

  dependencies:
    - build-site
