include:
  - project: 'platform/pipelines-templates'
    file: '/build/node/template-node-npm.yml'
    ref: master

install-dependencies:
  stage: prepare

  before_script:
    - npm version

  script:
    - echo "${PRIVATE_NPM_REGISTRY_TOKEN}" > ${HOME}/.npmrc
    - npm ci

  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - node_modules

test:
  stage: test

  coverage: '/^Statements\s*:\s*([^%]+)/'
  script:
    - npm run lint

  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - node_modules
    policy: pull

  artifacts:
    reports:
      cobertura: coverage/cobertura-coverage.xml

build-site:
  stage: post-test

  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - node_modules
      - build

  variables:
    NODE_ENV: "production"
    INLINE_RUNTIME_CHUNK: "false"

  script:
     - npm run build

  only:
    - master
    - tags

  artifacts:
    when: on_success
    expire_in: 1 day
    paths:
      - build

.docker-job:

  variables:
    COMMIT_SHA_FILEPATH: /usr/static/commit.sha
    IMAGE_NAME: feriapp/gestione-ore-website

  dependencies:
    - build-site
