include:
  - project: 'platform/pipelines-templates'
    file: '/build/node/template-node-npm.yml'
    ref: master

.docker-job:

  variables:
    COMMIT_SHA_FILEPATH: /etc/nginx/commit.sha
    IMAGE_NAME: feriapp/gestione-ore-website

